---
# Latest Hugo image
image: alpine:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  # Install Hugo
  - apk add hugo
  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ## Add the SSH key
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa

build:
  stage: build
  script:
    - hugo
  only:
    - master

deploy:
  stage: deploy
  script:
    - ssh -c 'sudo deploy_blog' ghost@blog.stormhub.io:31187
  only:
    - master
