---
# Latest Hugo image
image: alpine:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  # Install Hugo and SSH
  - apk update
  - apk add hugo
  - apk add openssh
  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ## Add the SSH private key and host key
  - ssh-keyscan blog.stormhub.io >> ~/.ssh/known_hosts
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa

build:
  stage: build
  script:
    - hugo
  only:
    - master

deploy:
  stage: deploy
  script:
    - ssh -i ~/.ssh/id_rsa -p31187 ghost@blog.stormhub.io 'sudo deploy_blog'
  only:
    - master
